name: Apply YAML configs

on:
  push:
    branches:
      - main

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up kubectl (add AWS CLI if using EKS)
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          kubectl-version: "latest"

      # Step 3: Configure AWS credentials for EKS (only needed for AWS EKS)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"

      # Step 4: Apply YAML changes to Kubernetes
      - name: Apply Kubernetes Configurations
        run: |
          kubectl apply -f ./*.yaml
